In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler,RobustScaler
from scipy import stats 
from scipy.stats import skew,kurtosis

In [6]:
path = input("Please enter the path of your csv file: ")
path

'C:\\Users\\Devadarsan\\Desktop\\Karthik_projects\\EDA_Package\\EDA_python_package_library\\layoffs_data.csv'

In [7]:
df = pd.read_csv(path)
df

,Company,Location_HQ,Industry,Laid_Off_Count,Date,Source,Funds_Raised,Stage,Date_Added,Country,Percentage,List_of_Employees_Laid_Off
0,Oda,Oslo,Food,150.0,2024-06-05,https://techcrunch.com/2024/06/05/softbank-bac...,691.0,Unknown,2024-06-05 18:01:25,Norway,NaN,Unknown
1,Pagaya,Tel Aviv,Finance,100.0,2024-06-05,https://www.calcalistech.com/ctechnews/article...,2000.0,Post-IPO,2024-06-05 23:11:24,Israel,0.20,Unknown
2,Aleph Farms,Tel Aviv,Food,30.0,2024-06-05,https://www.calcalistech.com/ctechnews/article...,119.0,Unknown,2024-06-05 23:13:43,Israel,0.30,Unknown
3,MoonPay,Dover,Crypto,30.0,2024-06-05,https://www.theblock.co/post/298638/moonpay-la...,651.0,Unknown,2024-06-05 23:12:47,United States,0.10,Unknown
4,Yext,New York City,Marketing,NaN,2024-06-05,https://www.investing.com/news/economy-news/ye...,117.0,Post-IPO,2024-06-05 18:02:40,United States,0.12,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...
3637,Service,Los Angeles,Travel,NaN,2020-03-16,https://techcrunch.com/2020/03/16/travel-savin...,5.1,Seed,2020-08-31 15:17:26,United States,1.00,Unknown
3638,HopSkipDrive,Los Angeles,Transportation,8.0,2020-03-13,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,45.0,Unknown,2020-04-03 04:47:03,United States,0.10,Unknown
3639,Panda Squad,SF Bay Area,Consumer,6.0,2020-03-13,https://twitter.com/danielsinger/status/123854...,1.0,Seed,2020-04-17 00:12:49,United States,0.75,Unknown
3640,Tamara Mellon,Los Angeles,Retail,20.0,2020-03-12,https://layoffs.fyi/list/tamara-mellon/,90.0,Series C,2020-03-31 16:04:23,United States,0.40,Unknown
3641,EasyPost,Salt Lake City,Logistics,75.0,2020-03-11,https://www.bizjournals.com/louisville/news/20...,12.0,Series A,2020-03-31 13:21:54,United States,NaN,Unknown

<h1>Initial Inspection<h1>

In [ ]:
class Inspection():

    def __init__(df):
        df = df
    
    def inspect():
        size = df.size
        shape = df.shape
        dimentions = df.ndim
        info = df.info()
        summary = df.describe()
        columns = df.columns
        n_col = len(columns)
        types = df.dtypes()
        duplicated = df.duplicated().sum()
        p_dup = duplicated / (len(df)*100)
        missing = df.isnull().sum()
        p_miss = missing / (len(df)*100)
        numeric = df.select_dtypes(include=['int64','float64'])
        n_num = len(numeric)
        categoical = df.select_dtypes(exclude=['int64','float64'])
        n_cat = len(categoical)
        datetime = df.select_dtypes(include=['datetime64'])
        corr = df.corr(numeric_only=True)

<h1>Missing values handling<h1>

In [ ]:
class MissingValueHandler():

    def __init__(df):
        df = df
    
    def mean():
        pass

    def median():
        pass

    def mode():
        pass

    def b_fill():
        pass

    def f_fill():
        pass

    def linear():
        pass

    def polynomial():
        pass

    def drop():
        pass

<h1>Outlier Handler<h1>

In [ ]:
class OutlierHander():

    def __init__(df):
        df = df
    
    def iqr_capping():
        pass

    def zscore_capping():
        pass


<h1>Scaling<h1>

In [10]:
class NumericalScaler():

    def __init__(df):
        df = df
    
    def standardscaler():
        pass

    def robustscaler():
        pass

<h1>Variable Transformation<h1>

In [12]:
class VariableTransformer():

    def __init__(df):
        df = df

    def binner():
        pass

    def log_transformer():
        pass

    def sqrt_transformer():
        pass

    def onehot_encoder():
        pass

    def label_encoder():
        pass